# ctxctx Configuration File
# This file allows you to customize the behavior of ctxctx for your project.
# For more details, see the project's documentation.

ROOT: .
OUTPUT_FILE_BASE_NAME: prompt_input_files
OUTPUT_FORMATS:
- md
- json
TREE_MAX_DEPTH: 3
TREE_EXCLUDE_EMPTY_DIRS: false
SEARCH_MAX_DEPTH: 5
MAX_MATCHES_PER_QUERY: 5
EXPLICIT_IGNORE_NAMES:
- .DS_Store
- .ctxctx.yaml
- .ctxctx_cache
- .git
- .gitignore
- .idea
- .venv
- .vscode
- __pycache__
- build
- coverage
- dist
- logs
- node_modules
- prompt_input_files.json
- prompt_input_files.md
- temp
- tmp
SUBSTRING_IGNORE_PATTERNS:
- package-lock.json
- playwright-report
- yarn.lock
- npm-debug.log
- .env
- __snapshots__
- .next
ADDITIONAL_IGNORE_FILENAMES:
- .dockerignore
- .npmignore
- .eslintignore
DEFAULT_CONFIG_FILENAME: .ctxctx.yaml
USE_GITIGNORE: true
GITIGNORE_PATH: .gitignore
USE_CACHE: true

# Profiles are defined directly within this file.
# You can define named sets of include/exclude rules and queries here.
profiles:
  example:
    description: An example profile.
    include:
    - src/**/*.py
    - docs/*.md
    exclude:
    - src/legacy/**
    queries:
    - README.md:1,20
